services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - ALPHA_ADVANTAGE_API_KEY=${ALPHA_ADVANTAGE_API_KEY}
    volumes:
      - ./authorized_users.json:/app/authorized_users.json:ro
      - /etc/letsencrypt/live/stocks.nikhilgarg.com/fullchain.pem:/app/cert.pem:ro 
      - /etc/letsencrypt/live/stocks.nikhilgarg.com/privkey.pem:/app/key.pem:ro 
    network_mode: bridge
    restart: unless-stopped
