version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - PORT=80
      - ALPHA_ADVANTAGE_API_KEY=${ALPHA_ADVANTAGE_API_KEY}
    volumes:
      - ./authorized_users.json:/app/authorized_users.json:ro
      - ./database.sqlite:/app/database.sqlite:rw
